name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make-debug
      run: make MODE=debug
    - name: make-release
      run: make MODE=release
    - name: make-test
      run: make MODE=debug test
